### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by layornos** [rju/architecture-evaluation-tool#7]
Hi, "out of the box" the projects have many errors. What is necessary to get it working (i.e. plug ins, Eclipse version)?

----

# Solution

## Terminal
* Compile with Java 8, it does not compile with > Java 8
* Tested with Maven v3.6.0 on Linux and MacOS
* Does not compile on the Windows Linux Subsystem!

## Eclipse
* Import Maven Projects
* Set API-Baseline
* Required Plugins  
** [PCM v4.0](https://sdqweb.ipd.kit.edu/wiki/PCM_Installation)
** [Geco](http://build.se.informatik.uni-kiel.de/eus/geco/snapshot/)
** [Klighd](http://rtsys.informatik.uni-kiel.de/~kieler/updatesite/nightly-openkieler/) (Without Ptolemy)
* Clean/Build

**Comment by rju** [comment]
Hi Sandro,

while compiling the project in its current state (from master branch),
it failed on my machine using 'mvn compile'. It looks like that the
geco framework has already been updated to more current version of
xtext and xtend, while the analysis tool has not. 

I've fixed the project. So far it compiles. It will be published
eventually, when jenkins has finished building it.

If will appear at
https://maui.se.informatik.uni-kiel.de/repo/se/snapshot/

At the moment, the last build is residing there from 04.06.2018.

Kind regards
Reiner

p.s. the source on github is already updated.

-- 
Dr.-Ing. Reiner Jung, Software Engineering Group
Dept. Computer Science, Kiel University, D-24118 Kiel, Germany
Tel: +49 (0)431 880-2776, Fax: -7617
Email: reiner.jung@email.uni-kiel.de
http://se.informatik.uni-kiel.de/

**Comment by layornos** [comment]
Hi Reiner!

Thank you for your fast reply.
Unfortunately, if I run ```mvn compile``` the following error occurs:
```
[INFO] Adding repository https://maui.se.informatik.uni-kiel.de/repo/geco/release/1.0.0
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'geco' from location https://maui.se.informatik.uni-kiel.de/repo/geco/release/1.0.0/: Unable to read repository at https://maui.se.informatik.uni-kiel.de/repo/geco/release/1.0.0/content.xml. Received fatal alert: handshake_failure -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'geco' from location https://maui.se.informatik.uni-kiel.de/repo/geco/release/1.0.0/
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Failed to load p2 repository with ID 'geco' from location https://maui.se.informatik.uni-kiel.de/repo/geco/release/1.0.0/
        at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:302)
        at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.gatherExternalInstallableUnits(TargetPlatformFactoryImpl.java:270)
        at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:176)
        at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:128)
        at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:1)
        at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform(ReactorRepositoryManagerImpl.java:84)
        at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform(P2DependencyResolver.java:224)
        at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:109)
        at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:95)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        ... 11 more
Caused by: org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at https://maui.se.informatik.uni-kiel.de/repo/geco/release/1.0.0/content.xml.
        at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:243)
        at org.eclipse.tycho.p2.remote.RemoteRepositoryCacheManager.createCache(RemoteRepositoryCacheManager.java:67)
        at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.getLocalFile(SimpleMetadataRepositoryFactory.java:66)
        at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:86)
        at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:60)
        at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:767)
        at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
        at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
        at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:61)
        at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:53)
        at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:298)
        ... 22 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alerts.getSSLException(java.base@9-internal/Alerts.java:198)
        at sun.security.ssl.Alerts.getSSLException(java.base@9-internal/Alerts.java:159)
        at sun.security.ssl.SSLSocketImpl.recvAlert(java.base@9-internal/SSLSocketImpl.java:2021)
        at sun.security.ssl.SSLSocketImpl.processInputRecord(java.base@9-internal/SSLSocketImpl.java:1189)
        at sun.security.ssl.SSLSocketImpl.readRecord(java.base@9-internal/SSLSocketImpl.java:1056)
        at sun.security.ssl.SSLSocketImpl.readRecord(java.base@9-internal/SSLSocketImpl.java:955)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(java.base@9-internal/SSLSocketImpl.java:1382)
        at sun.security.ssl.SSLSocketImpl.startHandshake(java.base@9-internal/SSLSocketImpl.java:1409)
        at sun.security.ssl.SSLSocketImpl.startHandshake(java.base@9-internal/SSLSocketImpl.java:1393)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:553)
        at org.eclipse.ecf.provider.filetransfer.httpclient4.SNIAwareHttpClient$1.connectSocket(SNIAwareHttpClient.java:64)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:263)
        at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

**Comment by rju** [comment]
On Fri, 01 Feb 2019 12:54:03 -0800
Sandro Koch <notifications@github.com> wrote:

> Hi Reiner!
> 
> Thank you for your fast reply.
> Unfortunately, if I run ```mvn compile``` the following error occurs:

can you open
https://maui.se.informatik.uni-kiel.de/repo/geco/release/1.0.0
in a browser window?

This works for me from home (outside of the university). From where do
you try to use this resource?

Kind regards
Reiner

> ```
> [INFO] Adding repository
> https://maui.se.informatik.uni-kiel.de/repo/geco/release/1.0.0
> [ERROR] Internal error: java.lang.RuntimeException: Failed to load p2
> repository with ID 'geco' from location
> https://maui.se.informatik.uni-kiel.de/repo/geco/release/1.0.0/:
> Unable to read repository at
> https://maui.se.informatik.uni-kiel.de/repo/geco/release/1.0.0/content.xml.
> Received fatal alert: handshake_failure -> [Help 1]
> org.apache.maven.InternalErrorException: Internal error:
> java.lang.RuntimeException: Failed to load p2 repository with ID
> 'geco' from location
> https://maui.se.informatik.uni-kiel.de/repo/geco/release/1.0.0/ at
> org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121) at
> org.apache.maven.cli.MavenCli.execute(MavenCli.java:863) at
> org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288) at
> org.apache.maven.cli.MavenCli.main(MavenCli.java:199) at
> sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native
> Method) at
> sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
> at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
> at
> java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: java.lang.RuntimeException: Failed to load p2 repository
> with ID 'geco' from location
> https://maui.se.informatik.uni-kiel.de/repo/geco/release/1.0.0/ at
> org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:302)
> at
> org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.gatherExternalInstallableUnits(TargetPlatformFactoryImpl.java:270)
> at
> org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:176)
> at
> org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:128)
> at
> org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:1)
> at
> org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform(ReactorRepositoryManagerImpl.java:84)
> at
> org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform(P2DependencyResolver.java:224)
> at
> org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:109)
> at
> org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:95)
> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266) at
> org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193) at
> org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106) ... 11
> more Caused by: org.eclipse.equinox.p2.core.ProvisionException:
> Unable to read repository at
> https://maui.se.informatik.uni-kiel.de/repo/geco/release/1.0.0/content.xml.
> at
> org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:243)
> at
> org.eclipse.tycho.p2.remote.RemoteRepositoryCacheManager.createCache(RemoteRepositoryCacheManager.java:67)
> at
> org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.getLocalFile(SimpleMetadataRepositoryFactory.java:66)
> at
> org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:86)
> at
> org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:60)
> at
> org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:767)
> at
> org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
> at
> org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:107)
> at
> org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:61)
> at
> org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:53)
> at
> org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:298) ...
> 22 more Caused by: javax.net.ssl.SSLHandshakeException: Received
> fatal alert: handshake_failure at
> sun.security.ssl.Alerts.getSSLException(java.base@9-internal/Alerts.java:198)
> at
> sun.security.ssl.Alerts.getSSLException(java.base@9-internal/Alerts.java:159)
> at
> sun.security.ssl.SSLSocketImpl.recvAlert(java.base@9-internal/SSLSocketImpl.java:2021)
> at
> sun.security.ssl.SSLSocketImpl.processInputRecord(java.base@9-internal/SSLSocketImpl.java:1189)
> at
> sun.security.ssl.SSLSocketImpl.readRecord(java.base@9-internal/SSLSocketImpl.java:1056)
> at
> sun.security.ssl.SSLSocketImpl.readRecord(java.base@9-internal/SSLSocketImpl.java:955)
> at
> sun.security.ssl.SSLSocketImpl.performInitialHandshake(java.base@9-internal/SSLSocketImpl.java:1382)
> at
> sun.security.ssl.SSLSocketImpl.startHandshake(java.base@9-internal/SSLSocketImpl.java:1409)
> at
> sun.security.ssl.SSLSocketImpl.startHandshake(java.base@9-internal/SSLSocketImpl.java:1393)
> at
> org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:553)
> at
> org.eclipse.ecf.provider.filetransfer.httpclient4.SNIAwareHttpClient$1.connectSocket(SNIAwareHttpClient.java:64)
> at
> org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)
> at
> org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
> at
> org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
> at
> org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
> at
> org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
> at
> org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
> at
> org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
> at
> org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:263)
> at
> org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
> at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60) [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with
> the -e switch. [ERROR] Re-run Maven using the -X switch to enable
> full debug logging. [ERROR] [ERROR] For more information about the
> errors and possible solutions, please read the following articles:
> [ERROR] [Help 1]
> http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
> ```
> 



-- 
Dr.-Ing. Reiner Jung, Software Engineering Group
Dept. Computer Science, Kiel University, D-24118 Kiel, Germany
Tel: +49 (0)431 880-2776, Fax: -7617
Email: reiner.jung@email.uni-kiel.de
http://se.informatik.uni-kiel.de/

**Comment by layornos** [comment]
I am also @home at the moment.

The link you provided directs me to:
https://maui.se.informatik.uni-kiel.de/repogeco/release/1.0.0/
which I cannot open.

But if I copy and paste the link, I can access the following website:
![image](https://user-images.githubusercontent.com/16957556/52153690-4a3f3500-267b-11e9-8617-5acf78bd18e3.png)

**Comment by rju** [comment]
Hi Sandro,

a compiled version in form of an Eclipse repository can be found at
https://maui.se.informatik.uni-kiel.de/repo/se/snapshot/

In case you have further issues. Maybe we should phone to identify the
issue.

Kind regards
Reiner

On Fri, 01 Feb 2019 14:45:30 -0800
Sandro Koch <notifications@github.com> wrote:

> I am also @home at the moment.
> 
> The link you provided directs me to:
> https://maui.se.informatik.uni-kiel.de/repogeco/release/1.0.0/
> which I cannot open.
> 
> But if I copy and paste the link, I can access the following website:
> ![image](https://user-images.githubusercontent.com/16957556/52153690-4a3f3500-267b-11e9-8617-5acf78bd18e3.png)
> 
> 



-- 
Dr.-Ing. Reiner Jung, Software Engineering Group
Dept. Computer Science, Kiel University, D-24118 Kiel, Germany
Tel: +49 (0)431 880-2776, Fax: -7617
Email: reiner.jung@email.uni-kiel.de
http://se.informatik.uni-kiel.de/

**Comment by layornos** [comment]
Hi Reiner,

thank you for your support.
I've tried to compile it on the Linux Subsystem on Windows, this could be the problem.
At work I cloned the repository and then I tried to compile it.
The error is not the same, but I get still an error. :D

Maven 3.6.0 creates the following error:
```
[INFO] Static software analysis based an hypergraphs ...... SUCCESS [  0.002 s]
[INFO] Software Evaluation ................................ FAILURE [ 31.870 s]
[INFO] Software Evaluation - Visualization ................ SKIPPED
[INFO] Software Evaluation - Java ......................... SKIPPED
[INFO] Software Evaluation - EMF Models ................... SKIPPED
[INFO] Software Evaluation - GECO Models .................. SKIPPED
[INFO] Software Evaluation - PCM Models ................... SKIPPED
[INFO] Software Evaluation - Java Feature ................. SKIPPED
[INFO] Software Evaluation - EMF Feature .................. SKIPPED
[INFO] Software Evaluation - GECO Feature ................. SKIPPED
[INFO] Software Evaluation - PCM Feature .................. SKIPPED
[INFO] Software Evaluation - Feature ...................... SKIPPED
[INFO] Software Evaluation - Target Platform .............. SKIPPED
[INFO] Software Evaluation - Update Site .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:30 min
[INFO] Finished at: 2019-02-04T09:22:31+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.3.0:compile (default-compile) on project de.cau.cs.se.software.evaluation: Compilation failure: Compilation failure: 
[ERROR] /Users/layornos/Projects/rju_arch_eval/de.cau.cs.se.software.evaluation/model-gen/de/cau/cs/se/software/evaluation/hypergraph/impl/HypergraphFactoryImpl.java:[22] 
[ERROR] 	public class HypergraphFactoryImpl extends EFactoryImpl implements HypergraphFactory {
[ERROR] 	             ^^^^^^^^^^^^^^^^^^^^^
[ERROR] The type HypergraphFactoryImpl must implement the inherited abstract method HypergraphFactory.createModule()
[ERROR] /Users/layornos/Projects/rju_arch_eval/de.cau.cs.se.software.evaluation/model-gen/de/cau/cs/se/software/evaluation/hypergraph/impl/HypergraphFactoryImpl.java:[138] 
[ERROR] 	public Module createModule() {
[ERROR] 	       ^^^^^^
[ERROR] The type Module is ambiguous
[ERROR] /Users/layornos/Projects/rju_arch_eval/de.cau.cs.se.software.evaluation/model-gen/de/cau/cs/se/software/evaluation/hypergraph/util/HypergraphAdapterFactory.java:[79] 
[ERROR] 	public Adapter caseModule(Module object) {
[ERROR] 	                          ^^^^^^
[ERROR] The type Module is ambiguous
[ERROR] /Users/layornos/Projects/rju_arch_eval/de.cau.cs.se.software.evaluation/model-gen/de/cau/cs/se/software/evaluation/hypergraph/util/HypergraphSwitch.java:[83] 
[ERROR] 	Module module = (Module)theEObject;
[ERROR] 	^^^^^^
[ERROR] The type Module is ambiguous
[ERROR] /Users/layornos/Projects/rju_arch_eval/de.cau.cs.se.software.evaluation/model-gen/de/cau/cs/se/software/evaluation/hypergraph/util/HypergraphSwitch.java:[83] 
[ERROR] 	Module module = (Module)theEObject;
[ERROR] 	                 ^^^^^^
[ERROR] The type Module is ambiguous
[ERROR] /Users/layornos/Projects/rju_arch_eval/de.cau.cs.se.software.evaluation/model-gen/de/cau/cs/se/software/evaluation/hypergraph/util/HypergraphSwitch.java:[240] 
[ERROR] 	public T caseModule(Module object) {
[ERROR] 	                    ^^^^^^
[ERROR] The type Module is ambiguous
[ERROR] 6 problems (6 errors)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :de.cau.cs.se.software.evaluation
```

I also tried maven 3.5.4, which creates the following error:
```
[INFO] Static software analysis based an hypergraphs 1.0.0-SNAPSHOT SUCCESS [  0.025 s]
[INFO] Software Evaluation ................................ SUCCESS [ 43.548 s]
[INFO] Software Evaluation - Visualization ................ SUCCESS [  3.174 s]
[INFO] Software Evaluation - Java ......................... FAILURE [  2.647 s]
[INFO] Software Evaluation - EMF Models ................... SKIPPED
[INFO] Software Evaluation - GECO Models .................. SKIPPED
[INFO] Software Evaluation - PCM Models ................... SKIPPED
[INFO] Software Evaluation - Java Feature ................. SKIPPED
[INFO] Software Evaluation - EMF Feature .................. SKIPPED
[INFO] Software Evaluation - GECO Feature ................. SKIPPED
[INFO] Software Evaluation - PCM Feature .................. SKIPPED
[INFO] Software Evaluation - Feature ...................... SKIPPED
[INFO] Software Evaluation - Target Platform .............. SKIPPED
[INFO] Software Evaluation - Update Site 1.0.0-SNAPSHOT ... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:39 min
[INFO] Finished at: 2019-02-04T09:40:56+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.16.0:compile (default) on project de.cau.cs.se.software.evaluation.java: Error compiling xtend sources in '/Users/layornos/Projects/rju_arch_eval/de.cau.cs.se.software.evaluation.java/src'. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.16.0:compile (default) on project de.cau.cs.se.software.evaluation.java: Error compiling xtend sources in '/Users/layornos/Projects/rju_arch_eval/de.cau.cs.se.software.evaluation.java/src'.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error compiling xtend sources in '/Users/layornos/Projects/rju_arch_eval/de.cau.cs.se.software.evaluation.java/src'.
    at org.eclipse.xtend.maven.AbstractXtendCompilerMojo.compile (AbstractXtendCompilerMojo.java:177)
    at org.eclipse.xtend.maven.XtendCompile.internalExecute (XtendCompile.java:63)
    at org.eclipse.xtend.maven.AbstractXtendMojo.execute (AbstractXtendMojo.java:42)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :de.cau.cs.se.software.evaluation.java
```

**Comment by layornos** [comment]
Solution see first post

**Comment by rju** [comment]
Thanks a lot. Will be added to the documentation ;-)
